# Generated by Django 3.1.1 on 2020-10-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plan', models.CharField(choices=[('Wordpress SSD', 'Wordpress SSD'), ('Basico SSD', 'Basico SSD'), ('Emprendedor SSD', 'Emprendedor SSD'), ('Corporativo SSD', 'Corporativo SSD')], max_length=50)),
                ('vigencia', models.CharField(choices=[('1 año', '1 años'), ('2 años', '2 años'), ('3 años', '3 años'), ('4 años', '4 años')], max_length=50)),
                ('dominio', models.CharField(max_length=100)),
                ('cert_ssl', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('a_paterno', models.CharField(max_length=100)),
                ('a_materno', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
