# Generated by Django 3.1.1 on 2020-10-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dominio',
            field=models.URLField(max_length=100),
        ),
    ]
