# Generated by Django 3.1.1 on 2020-10-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_auto_20201022_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cert_ssl',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
    ]
