# Generated by Django 3.1.1 on 2020-10-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20201022_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='a_materno',
            field=models.CharField(max_length=100, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='a_paterno',
            field=models.CharField(max_length=100, verbose_name='Apellido Paterno'),
        ),
    ]
