# Generated by Django 3.1.1 on 2020-10-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_auto_20201022_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('f_cumple', models.DateField(blank=True, null=True, verbose_name='Fecha de cumpleaños')),
                ('tipo_consulta', models.IntegerField(choices=[(0, 'Consulta'), (1, 'Reclamo'), (2, 'Sugerencia'), (3, 'Felicitaciones')])),
                ('mensaje', models.TextField(max_length=200)),
                ('avisos', models.BooleanField(verbose_name='¿Desea recibir información adicional a su email?')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cert_ssl',
            field=models.BooleanField(blank=True, verbose_name='¿Requiere Certificado SSL?'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='rut',
            field=models.CharField(max_length=10),
        ),
    ]
