# Generated by Django 3.1.1 on 2020-10-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_auto_20201027_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='f_cumple',
        ),
    ]
