# Generated by Django 3.1.1 on 2020-11-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_auto_20201103_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_plan',
            field=models.IntegerField(choices=[(24990, 'Wordpress SSD'), (34990, 'Basico SSD'), (44990, 'Emprendedor SSD'), (54990, 'Corporativo SSD')]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='vigencia',
            field=models.IntegerField(choices=[(1, '1 año'), (2, '2 años'), (3, '3 años'), (4, '4 años')]),
        ),
    ]
